# Docker Compose configuration for a PHP development environment with Nginx, PHP 8.4 FPM, and SQL and No-SQL databases
# This setup includes MySQL, and MongoDB as database options
# All rights reserved (2025 Vinícius Cordeiro <vinicordeirogo@gmail.com>)
services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/errors:/usr/share/nginx/html/errors:ro
    depends_on:
      - php

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_8.4_fpm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
      - "9003:9003"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  
  node:
    image: node:alpine
    container_name: node
    volumes:
      - ./src:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongodb:/var/lib/mongodb:rw
    ports:
      - "27017:27017"

volumes:
  mysql_data:
  mongodb_data:
